[package]
name = "tinysys-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-io = { version = "0.6", features = ["alloc"] }

tinysys-sys = { git = "https://github.com/Chris--B/tinysys-rs.git" }
# tinysys-sys = { path = "../tinysys-sys" }

[features]
default = []
std = []
